New: update-tailscale; rpm-based: added exit codes

diff --git a/rpm-based/rpm-name b/rpm-based/rpm-name
--- a/rpm-based/rpm-name
+++ b/rpm-based/rpm-name
@@ -5,7 +5,7 @@
 #  RPM File Rename (rpm-name)
 #
 #  Jason Bowman (bowmanjc)
-#  03 July 2022
+#  31 March 2023
 #
 #  Purpose: This bash script provides an easy tool to update
 #           rpm package filenames based on the following info
@@ -26,17 +26,23 @@
 #  Dependencies: This script requires file & rpm in order to
 #                execute.
 #
+#  Exit status: 0 if any input rpm file is renamed, 1 otherwise
+#
 #  License: GNU GPLv3
 #
 ##################################################################
 
+STATUS=1
 for rpmfile in "$@"
 do
    if [[ $(file --mime-type -b "$rpmfile") == application/x-rpm ]]; then
       # had to switch from (i)nteractive to (f)orce to use in ansible playbook
       mv -vf $rpmfile $(rpm -qp --nosignature $rpmfile).rpm
+      if [[ $? == 0 ]]; then
+         STATUS=0
+      fi
    else
       echo "[!] Warning: $rpmfile is not an rpm package. Skipping."
    fi
 done
-exit 0
+exit $STATUS
diff --git a/rpm-based/update-local-repo b/rpm-based/update-local-repo
--- a/rpm-based/update-local-repo
+++ b/rpm-based/update-local-repo
@@ -5,7 +5,7 @@
 #  Update Local Repository (update-local-repo)
 #
 #  Jason Bowman (bowmanjc)
-#  19 November 2020
+#  31 March 2023
 #
 #  Purpose: This bash script provides an easy tool to update your
 #           local repository after downloading an rpm package file.
@@ -31,28 +31,32 @@
 #           gpgcheck=0
 #           metadata_expire=60
 #
+#  Exit status: 0 if any rpm files are moved to the repo directory,
+#               2 if source directory cannot be determined, 1 otherwise
+#
 #  License: GNU GPLv3
 #
 ##################################################################
 
+STATUS=1
 OS=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
 BASE="/var/www/html/"$OS"/updates"
 VER=$(lsb_release -sr)
 ARCH=$(uname -m)
 
-[ -d $BASE/$VER/$ARCH ] || mkdir -p $BASE/$VER/$ARCH
+[[ -d $BASE/$VER/$ARCH ]] || mkdir -p $BASE/$VER/$ARCH
 
-if [ -z $SUDO_USER ]
-then
-    if [ -z $HOME ]
-    then
+if [[ -z $SUDO_USER ]]; then
+    if [[ -z $HOME ]]; then
         echo "[!] Error: Unable to determine directory to retrieve rpm packages"
-        exit 1
+        exit 2
     else
         mv -v $HOME/Downloads/*.rpm $BASE/$VER/$ARCH 2> /dev/null
+        STATUS=$?
     fi
 else
     mv -v /home/$SUDO_USER/Downloads/*.rpm $BASE/$VER/$ARCH 2> /dev/null
+    STATUS=$?
 fi
 
 cd $BASE/$VER/$ARCH
@@ -60,4 +64,4 @@ chown -c root:root *.rpm
 chmod -c 644 *.rpm
 createrepo $BASE/$VER/$ARCH
 
-exit 0
+exit $STATUS
